"""create Candidate, Position, Stage, Status and CandidateStage models

Revision ID: 623f1b296499
Revises: 34f482caa1ab
Create Date: 2022-11-25 11:40:20.101585

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '623f1b296499'
down_revision = '34f482caa1ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('cv_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_stage',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('candidate_id', 'stage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_stage')
    op.drop_table('status')
    op.drop_table('candidate')
    op.drop_table('stage')
    op.drop_table('position')
    # ### end Alembic commands ###
